log = trash/arasim.$(SIGMA).$(ENERGY).$(Process).log
output = trash/arasim.$(SIGMA).$(ENERGY).$(Process).out
error = trash/arasim.$(SIGMA).$(ENERGY).$(Process).err

request_cpus = 1
request_memory = 4GB
request_disk = 5GB
#+OriginalTime=5400
+OriginalTime=600
Universe = vanilla
getenv = true

use_x509userproxy = true
Requirements = HAS_CVMFS_icecube_opensciencegrid_org && GLIDEIN_SITE=="MSU"

executable = job.sh
arguments = $(SIGMA) $(ENERGY) $(Process)

queue $(NUMBER)
